<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CommuneSeeder extends Seeder
{
    public function run(): void
    {
        $communes = [
            ['nom' => 'Abengourou', 'region' => 'Indénié-Djuablin'],
            ['nom' => 'Aboisso', 'region' => 'Sud-Comoé'],
            ['nom' => 'Adiaké', 'region' => 'Sud-Comoé'],
            ['nom' => 'Adzopé', 'region' => 'La Mé'],
            ['nom' => 'Agboville', 'region' => 'Agnéby-Tiassa'],
            ['nom' => 'Agnibilékrou', 'region' => 'Indénié-Djuablin'],
            ['nom' => 'Akoupé', 'region' => 'La Mé'],
            ['nom' => 'Alépé', 'region' => 'La Mé'],
            ['nom' => 'Anyama', 'region' => 'Abidjan'],
            ['nom' => 'Arrah', 'region' => 'Moronou'],
            ['nom' => 'Assinie', 'region' => 'Sud-Comoé'],
            ['nom' => 'Attécoubé', 'region' => 'Abidjan'],
            ['nom' => 'Attobrou', 'region' => 'Agnéby-Tiassa'],
            ['nom' => 'Ayamé', 'region' => 'Sud-Comoé'],
            ['nom' => 'Azaguié', 'region' => 'Agnéby-Tiassa'],
            ['nom' => 'Bako', 'region' => 'Bafing'],
            ['nom' => 'Bangolo', 'region' => 'Guémon'],
            ['nom' => 'Bassawa', 'region' => 'Hambol'],
            ['nom' => 'Bédiala', 'region' => 'Haut-Sassandra'],
            ['nom' => 'Béoumi', 'region' => 'Gbêkê'],
            ['nom' => 'Béttié', 'region' => 'Indénié-Djuablin'],
            ['nom' => 'Biankouma', 'region' => 'Tonkpi'],
            ['nom' => 'Bingerville', 'region' => 'Abidjan'],
            ['nom' => 'Bin-Houyé', 'region' => 'Tonkpi'],
            ['nom' => 'Bloléquin', 'region' => 'Cavally'],
            ['nom' => 'Bocanda', 'region' => 'N\'Zi'],
            ['nom' => 'Bodokro', 'region' => 'Gbêkê'],
            ['nom' => 'Bondoukou', 'region' => 'Gontougo'],
            ['nom' => 'Bongouanou', 'region' => 'Moronou'],
            ['nom' => 'Boniérédougou', 'region' => 'Tchologo'],
            ['nom' => 'Bonon', 'region' => 'Marahoué'],
            ['nom' => 'Bonoua', 'region' => 'Sud-Comoé'],
            ['nom' => 'Booko', 'region' => 'Kabadougou'],
            ['nom' => 'Borotou', 'region' => 'Bafing'],
            ['nom' => 'Botro', 'region' => 'Gbêkê'],
            ['nom' => 'Bouaflé', 'region' => 'Marahoué'],
            ['nom' => 'Bouaké', 'region' => 'Gbêkê'],
            ['nom' => 'Bouna', 'region' => 'Bounkani'],
            ['nom' => 'Boundiali', 'region' => 'Bagoué'],
            ['nom' => 'Brobo', 'region' => 'Gbêkê'],
            ['nom' => 'Buyo', 'region' => 'Nawa'],
            ['nom' => 'Cocody', 'region' => 'Abidjan'],
            ['nom' => 'Dabakala', 'region' => 'Hambol'],
            ['nom' => 'Dabou', 'region' => 'Grands-Ponts'],
            ['nom' => 'Daloa', 'region' => 'Haut-Sassandra'],
            ['nom' => 'Danané', 'region' => 'Tonkpi'],
            ['nom' => 'Daoukro', 'region' => 'Iffou'],
            ['nom' => 'Diabo', 'region' => 'Gbêkê'],
            ['nom' => 'Dianra', 'region' => 'Béré'],
            ['nom' => 'Diawala', 'region' => 'Tchologo'],
            ['nom' => 'Didiévi', 'region' => 'Bélier'],
            ['nom' => 'Diégonéfla', 'region' => 'Gôh'],
            ['nom' => 'Dikodougou', 'region' => 'Poro'],
            ['nom' => 'Dimbokro', 'region' => 'N\'Zi'],
            ['nom' => 'Divo', 'region' => 'Lôh-Djiboua'],
            ['nom' => 'Djebonoua', 'region' => 'Gbêkê'],
            ['nom' => 'Djèkanou', 'region' => 'Bélier'],
            ['nom' => 'Djouroutou', 'region' => 'San-Pédro'],
            ['nom' => 'Doropo', 'region' => 'Bounkani'],
            ['nom' => 'Duékoué', 'region' => 'Guémon'],
            ['nom' => 'Ferkessédougou', 'region' => 'Tchologo'],
            ['nom' => 'Fresco', 'region' => 'Gbôklè'],
            ['nom' => 'Gagnoa', 'region' => 'Gôh'],
            ['nom' => 'Gbeleban', 'region' => 'Kabadougou'],
            ['nom' => 'Gbon', 'region' => 'Bagoué'],
            ['nom' => 'Gohitafla', 'region' => 'Marahoué'],
            ['nom' => 'Goulia', 'region' => 'Folon'],
            ['nom' => 'Grand-Bassam', 'region' => 'Sud-Comoé'],
            ['nom' => 'Grand-Béréby', 'region' => 'San-Pédro'],
            ['nom' => 'Grand-Lahou', 'region' => 'Grands-Ponts'],
            ['nom' => 'Grand-Zattry', 'region' => 'Nawa'],
            ['nom' => 'Guéyo', 'region' => 'Nawa'],
            ['nom' => 'Guibéroua', 'region' => 'Gôh'],
            ['nom' => 'Guiembé', 'region' => 'Poro'],
            ['nom' => 'Guiglo', 'region' => 'Cavally'],
            ['nom' => 'Guintéguéla', 'region' => 'Bafing'],
            ['nom' => 'Issia', 'region' => 'Haut-Sassandra'],
            ['nom' => 'Jacqueville', 'region' => 'Grands-Ponts'],
            ['nom' => 'Kani', 'region' => 'Worodougou'],
            ['nom' => 'Kaniasso', 'region' => 'Folon'],
            ['nom' => 'Karakoro', 'region' => 'Poro'],
            ['nom' => 'Katiola', 'region' => 'Hambol'],
            ['nom' => 'Kokoumbo', 'region' => 'Bélier'],
            ['nom' => 'Kolian', 'region' => 'Bagoué'],
            ['nom' => 'Komborodougou', 'region' => 'Poro'],
            ['nom' => 'Kong', 'region' => 'Tchologo'],
            ['nom' => 'Koonan', 'region' => 'Bafing'],
            ['nom' => 'Korhogo', 'region' => 'Poro'],
            ['nom' => 'Koro', 'region' => 'Bafing'],
            ['nom' => 'Kouassi-Datékro', 'region' => 'Gontougo'],
            ['nom' => 'Kouassi-Kouassikro', 'region' => 'N\'Zi'],
            ['nom' => 'Kouibly', 'region' => 'Guémon'],
            ['nom' => 'Koumassi', 'region' => 'Abidjan'],
            ['nom' => 'Koun-Fao', 'region' => 'Gontougo'],
            ['nom' => 'Kounahiri', 'region' => 'Béré'],
            ['nom' => 'Kouto', 'region' => 'Bagoué'],
            ['nom' => 'Lakota', 'region' => 'Lôh-Djiboua'],
            ['nom' => 'Logoualé', 'region' => 'Tonkpi'],
            ['nom' => 'Madinani', 'region' => 'Kabadougou'],
            ['nom' => 'Maféré', 'region' => 'Sud-Comoé'],
            ['nom' => 'Man', 'region' => 'Tonkpi'],
            ['nom' => 'Mankono', 'region' => 'Béré'],
            ['nom' => 'Marcory', 'region' => 'Abidjan'],
            ['nom' => 'Massala', 'region' => 'Worodougou'],
            ['nom' => 'Mayo', 'region' => 'Nawa'],
            ['nom' => 'M\'bahiakro', 'region' => 'Iffou'],
            ['nom' => 'M\'batto', 'region' => 'Moronou'],
            ['nom' => 'M\'bengué', 'region' => 'Poro'],
            ['nom' => 'Méagui', 'region' => 'Nawa'],
            ['nom' => 'Minignan', 'region' => 'Folon'],
            ['nom' => 'Morondo', 'region' => 'Worodougou'],
            ['nom' => 'Nafana', 'region' => 'Poro'],
            ['nom' => 'Nassian', 'region' => 'Bounkani'],
            ['nom' => 'N\'douci', 'region' => 'Agnéby-Tiassa'],
            ['nom' => 'Niablé', 'region' => 'Indénié-Djuablin'],
            ['nom' => 'Niakaramandougou', 'region' => 'Hambol'],
            ['nom' => 'Niofoin', 'region' => 'Poro'],
            ['nom' => 'Odienné', 'region' => 'Kabadougou'],
            ['nom' => 'Ouaninou', 'region' => 'Bafing'],
            ['nom' => 'Ouellé', 'region' => 'Iffou'],
            ['nom' => 'Oumé', 'region' => 'Gôh'],
            ['nom' => 'Ouragahio', 'region' => 'Gôh'],
            ['nom' => 'Plateau', 'region' => 'Abidjan'],
            ['nom' => 'Port-Bouët', 'region' => 'Abidjan'],
            ['nom' => 'Prikro', 'region' => 'Iffou'],
            ['nom' => 'Rubino', 'region' => 'Agnéby-Tiassa'],
            ['nom' => 'Sakassou', 'region' => 'Gbêkê'],
            ['nom' => 'Samatiguila', 'region' => 'Kabadougou'],
            ['nom' => 'San-Pédro', 'region' => 'San-Pédro'],
            ['nom' => 'Sandégué', 'region' => 'Gontougo'],
            ['nom' => 'Sangouiné', 'region' => 'Tonkpi'],
            ['nom' => 'Sassandra', 'region' => 'Gbôklè'],
            ['nom' => 'Satama-Sokoro', 'region' => 'Hambol'],
            ['nom' => 'Satama-Sokoura', 'region' => 'Hambol'],
            ['nom' => 'Séguéla', 'region' => 'Worodougou'],
            ['nom' => 'Séguelon', 'region' => 'Kabadougou'],
            ['nom' => 'Seydougou', 'region' => 'Kabadougou'],
            ['nom' => 'Sifié', 'region' => 'Worodougou'],
            ['nom' => 'Sikensi', 'region' => 'Agnéby-Tiassa'],
            ['nom' => 'Sinématiali', 'region' => 'Poro'],
            ['nom' => 'Sinfra', 'region' => 'Marahoué'],
            ['nom' => 'Sipilou', 'region' => 'Tonkpi'],
            ['nom' => 'Soubré', 'region' => 'Nawa'],
            ['nom' => 'Songon', 'region' => 'Abidjan'],
            ['nom' => 'Taabo', 'region' => 'Agnéby-Tiassa'],
            ['nom' => 'Tabou', 'region' => 'San-Pédro'],
            ['nom' => 'Tafiré', 'region' => 'Hambol'],
            ['nom' => 'Taï', 'region' => 'Cavally'],
            ['nom' => 'Tanda', 'region' => 'Gontougo'],
            ['nom' => 'Téhini', 'region' => 'Bounkani'],
            ['nom' => 'Tengréla', 'region' => 'Bagoué'],
            ['nom' => 'Tiaporé', 'region' => 'Sud-Comoé'],
            ['nom' => 'Tiassalé', 'region' => 'Agnéby-Tiassa'],
            ['nom' => 'Tiédio', 'region' => 'Bagoué'],
            ['nom' => 'Tiénigboué', 'region' => 'Gbêkê'],
            ['nom' => 'Tioroniaradougou', 'region' => 'Poro'],
            ['nom' => 'Tiébissou', 'region' => 'Bélier'],
            ['nom' => 'Touba', 'region' => 'Bafing'],
            ['nom' => 'Toulépleu', 'region' => 'Cavally'],
            ['nom' => 'Toumodi', 'region' => 'Bélier'],
            ['nom' => 'Treichville', 'region' => 'Abidjan'],
            ['nom' => 'Transua', 'region' => 'Gontougo'],
            ['nom' => 'Vavoua', 'region' => 'Haut-Sassandra'],
            ['nom' => 'Yamoussoukro', 'region' => 'Yamoussoukro'],
            ['nom' => 'Yopougon', 'region' => 'Abidjan'],
            ['nom' => 'Zikisso', 'region' => 'Lôh-Djiboua'],
            ['nom' => 'Zouan-Hounien', 'region' => 'Tonkpi'],
            ['nom' => 'Zoukougbeu', 'region' => 'Haut-Sassandra'],
            ['nom' => 'Zuénoula', 'region' => 'Marahoué'],
        ];

        foreach ($communes as $commune) {
            DB::table('communes')->insert([
                'nom' => $commune['nom'],
                'region' => $commune['region'],
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        }
    }
}
